NDefines_Graphics = {

NWiki = {
	BASE_URL = "https://hoi4.paradoxwikis.com/",
	FORUM_URL = "https://forum.paradoxplaza.com/forum/index.php?forums/hearts-of-iron-iv.844/"
},

NMapMode = {
	FABRICATE_CLAIM_SELECTED_SECONDARY_COLOR = { 0, 1, 0, 1 },
	FABRICATE_CLAIM_TARGET_COUNTRY_SECONDARY_COLOR = { 0, 0, 0, 0 },
	FABRICATE_CLAIM_NON_TARGET_COUNTRY_SECONDARY_COLOR = { 0, 0, 0, 0 },
	FABRICATE_CLAIM_ALREADY_CLAIM_SECONDARY_COLOR = { 0.5, 0, 0, 1 },
	FABRICATE_CLAIM_ALREADY_CORE_SECONDARY_COLOR = { 0.5, 0, 0, 1 },
	CONSTRUCTION_MAP_MODE_BUILDING_DEFAULT_COLOR = { 0.43, 0.22, 0.22, 0.5 }, 			
	CONSTRUCTION_MAP_MODE_BUILDING_MAX_LEVEL_COLOR = { 0.05, 0.1, 0.7, 0.8 }, 			
	CONSTRUCTION_MAP_MODE_BUILDING_LEVEL_LOW_COLOR = { 0.2, 0.7, 0.0, 0.1 },
	CONSTRUCTION_MAP_MODE_BUILDING_LEVEL_HI_COLOR = { 0.4, 0.9, 0.0, 0.8 },
	CONSTRUCTION_MAP_MODE_BUILDING_MAX_AMOUNT_QUEUED_COLOR = { 0.0, 0.0, 1.0  }, 	
	CONSTRUCTION_MAP_MODE_BUILDING_QUEUED_COLOR = { 1.0, 0.85, 0.0  },				
	MAP_MODE_MANPOWER_RANGE_MAX = 20000000,											
	MAP_MODE_MANPOWER_RANGE_COLOR_FROM = { 0.2, 0.2, 0.7, 0.18 },					
	MAP_MODE_MANPOWER_RANGE_COLOR_TO = { 1, 0.125, 0.0, 0.6 },
	MAP_MODE_INFRA_RANGE_COLOR_FROM = { 1, 0.125, 0.0, 0.1 },						
	MAP_MODE_INFRA_RANGE_COLOR_TO = { 0.1, 0.9, 0.1, 0.6 },
	MAP_MODE_IDEOLOGY_COLOR_TRANSPARENCY = 1,										
	CONSTRUCTION_MAP_MODE_TRANSPARENCY_OVERRIDE = 241, 								
	PEACE_CONFERENCE_CURRENT_SELECTED_SECONDARY_COLOR = { 0, 0, 1, 0.25 },
	PEACE_CONFERENCE_SELECTABLE_SECONDARY_COLOR = { 0, 1, 0, 0.25 },
	PEACE_CONFERENCE_CONTESTED_SECONDARY_COLOR = { 1, 0, 0, 0.25 },
	PEACE_CONFERENCE_CHANGE_TARGET_TAG_SECONDARY_COLOR =  { 0, 0.8, 0.5, 0.25 },
	PEACE_CONFERENCE_DIFFERENT_STACKABLE_SECONDARY_COLOR =  { 1, 1, 0, 0.25 },
	FACTIONS_COLOR_NOT_MEMBER = { 0.6, 0.6, 0.6, 0.25 },
	FACTIONS_MEMBER_TRANSPARENCY = 1.0,
	PLAYER_MAPMODE_NOT_SELECTED_COUNTRY_TRANSPARENCY = 0.15,						
	SELECTED_COUNTRY_HIGHLIGHT_THICKNESS_MULT = 1.5,								
	STRATEGIC_MODE_COUNTRY_COLOR_STRIPES_TRANSP = 0.0,
	STRATEGIC_MODE_ENEMY_STRIPES_COLOR = { 0.827, 0.172, 0.184, 0.0 },
	STRATEGIC_MODE_OUR_STRIPES_COLOR = { 0.427, 0.619, 0.858, 0.0 },
	STRATEGIC_MODE_ALLY_STRIPES_COLOR = { 0.427, 0.619, 0.858, 0.0 },
	RADAR_RANGE_STRIPES_COLOR = { 1.0, 1.0, 0.0, 0.14 },
	RADAR_RANGE_COLOR = { 0.039, 0.627, 0.0, 1.0 },
	RADAR_RANGE_ALLIED_COLOR = { 0.0, 0.647, 1.0, 1.0 },
	RADAR_RANGE_SELECTED_COLOR = { 1.0, 1.0, 0.0, 1.0 },
	RADAR_ROTATION_SPEED = 0.0,  -- Modified by mod
	AIR_RANGE_CAN_ASSIGN_MISSION_STRIPES_COLOR = { 0, 0.8, 0, 0.0 },				
	AIR_RANGE_CANNOT_ASSIGN_MISSION_STRIPES_COLOR = { 0.8, 0, 0, 0.5 },
	AIR_RANGE_INDICATOR_DEFAULT_COLOR = { 1.0, 1.0, 0, 1 },							
	AIR_RANGE_INDICATOR_NO_WINGS_COLOR = { 1.0, 0, 0, 1 },							
	AIR_RANGE_INDICATOR_ROTATION_SPEED = 0.0000,  -- Modified by mod									
	AIR_MISSION_ARROW_ACTIVE_COLOR = { 0, 1.0, 0, 0.5 },							
	AIR_MISSION_ARROW_NONACTIVE_COLOR = { 1.0, 1.0, 1.0, 0.2 },						
	AIR_MISSION_ARROW_SELECTED_COLOR = { 1.0, 1.0, 0, 0.8 },						
	AIR_TRANSFER_ARROW_COLOR = { 1, 1, 0, 0.75 },									
	NAVAL_REGION_ACCESS_AVOID_COLOR = { 1, 1, 0, 0.35 },							
	NAVAL_REGION_ACCESS_BLOCK_COLOR = { 1, 0, 0, 0.45 },							
	NAVAL_REGION_FADE_WHEN_FLEET_SELECTED = 0.25,									
	AIR_REGION_FADE_WHEN_WING_SELECTED = 0.15,
	UI_CONFIGURABLE_SLOT_FROM = 4,													
	UI_CONFIGURABLE_SLOT_TO = 10,
	MAP_MODE_TERRAIN_TRANSPARENCY = 0.8,  -- Modified by mod											
	MAP_MODE_NAVAL_TERRAIN_TRANSPARENCY = 0.8,										
	MAP_MODE_INTEL_NETWORK_STRENGTH_COLOR_LOW = { 0.1, 0.1, 0.5, 0.2 },					
	MAP_MODE_INTEL_NETWORK_STRENGTH_COLOR_HIGH = { 0.4, 0.3, 0.9, 1.0 },					
	MAP_MODE_INTEL_NETWORK_STRENGTH_QUIET_COLOR_LOW = { 0.1, 0.5, 0.1, 0.2 },					
	MAP_MODE_INTEL_NETWORK_STRENGTH_QUIET_COLOR_HIGH = { 0.4, 0.9, 0.3, 1.0 },					
	MAP_MODE_INTEL_MAX_HORIZONTAL_STACK = 3,											
	RAILWAY_GUN_RANGE_INDICATOR_DEFAULT_COLOR = { 1.0, 1.0, 1.0, 1.0 },				
	RAILWAY_GUN_RANGE_INDICATOR_ROTATION_SPEED = 0.001,								
	RAILWAY_GUN_RANGE_STRIPES_COLOR = { 1.0, 0.5, 0.0, 0.2 },						

	PREPARING_RAID_ARROW_COLOR = { 0.7, 0.7, 0.7, 1.0 },							    
	READY_RAID_ARROW_COLOR = { 0.7, 0.7, 0, 0.9},							        
	ACTIVE_RAID_ARROW_COLOR = { 1, 0, 0, 0.9 },							        

	OCCUPATION_MAP_MODE_COUNTRY_STRIPE_ALPHA = 0.3,									
	OPERATIVE_MAP_MODE_INVALID_COUNTRY_TARGET_TRANSPARENCY = 0.15,							

	COASTAL_FACILITY_OFFSET = {-1.5, 0, 1.5},					

	SUPPLY_MAP_MODE_COUNTRY_BORDER_CAMERA_DISTANCE = 1.0,
	SUPPLY_MAP_MODE_COUNTRY_BORDER_OUTLINE_CUTOFF = 0.973,
	GRADIENT_BORDERS_THICKNESS_SUPPLY_COUNTRY_BORDER = 10.0,
	SUPPLY_COUNTRY_BORDER_PLAYER_COLOR = { 0.1, 0.66, 0.1, 1.0 },
	SUPPLY_COUNTRY_BORDER_FRIEND_COLOR = { 0.035, 0.426, 0.91, 1.0 },
	SUPPLY_COUNTRY_BORDER_ACCESS_COLOR = { 0.1, 0.66, 0.1, 1.0 },

	SUPPLY_MAP_MODE_REACH_COLOR = {
		0.0,   0.6, 0.0, 0.4, 1.0, 			
		0.02,  0.2, 0.17, 0.52, 1.0, 		
		0.12,  0.04, 0.17, 0.60, 1.0,		
		0.2,   0.13, 0.36, 0.65, 1.0,		
		0.4,   0.11, 0.56, 0.75, 1.0,		
		0.6,   0.25, 0.71, 0.76, 1.0,		
		0.8,   0.47, 0.8, 0.73, 1.0,		
		1.0,   0.6, 0.82, 0.6, 1.0,			
	}, 
	SUPPLY_MAP_MODE_BEST_FLOW_DISPLAY = 12, 
	SUPPLY_MAP_MODE_STATUS_COLOR = {
		0.0,   0.9, 0.0, 0.0, 1.0,			
		0.7,   0.98, 0.4, 0.1, 1.0,			
		1.0,   0.8, 0.64, 0.2, 1.0,			
	},
	SUPPLY_STATUS_DISPLAY_THRESHOLD = 0.90, 
	SUPPLY_HOVERED_STATE_COLOR_INDEX = 0, 
	SUPPLY_HOVERED_PROVINCE_COLOR_INDEX = 4, 
	PEACE_HOVERED_STATE_COLOR_INDEX = 3 , 
	PEACE_CLAIMED_STATE_COLOR_INDEX = 2 , 
	SELECTION_HOVERED_STATE_COLOR_INDEX_CONTROLLED = 5, 
	SELECTION_HOVERED_STATE_COLOR_INDEX_FOREIGN = 6,	
	CONSTRUCTION_PRIMARY_VALID_BUILD_TARGET_PROVINCE_COLOR_INDEX = 7,
	CONSTRUCTION_PRIMARY_INVALID_BUILD_TARGET_PROVINCE_COLOR_INDEX = 8,
	CONSTRUCTION_PRIMARY_FOREIGN_BUILD_TARGET_PROVINCE_COLOR_INDEX = 9,
	CONSTRUCTION_SECONDARY_VALID_BUILD_TARGET_PROVINCE_COLOR_INDEX = 10,
	CONSTRUCTION_SECONDARY_INVALID_BUILD_TARGET_PROVINCE_COLOR_INDEX = 11,
	CONSTRUCTION_SECONDARY_FOREIGN_BUILD_TARGET_PROVINCE_COLOR_INDEX = 12,

},

NMapIcons = {

	TOP_MAP_ICON = 30,
	INTERPOLATION_SNAP_DISTANCE = 0.3,
	INTEL_MAP_MODE_MAP_ICON_OFFSET = { 12, 40 },				
	COARSE_RAILWAY_GUN_POSITION_OFFSET = { 0, 0 },  -- Modified by mod			

	DEFAULT_PRIORITY_UNITS_STACK = 10,
	DEFAULT_PRIORITY_UNITS_STACK_GROUP = 11,
	DEFAULT_PRIORITY_VICTORY_POINTS = 5,
	DEFAULT_PRIORITY_RESOURCE = 10,
	DEFAULT_PRIORITY_CONSTRUCTION_INFO = 3,
	DEFAULT_PRIORITY_AIR_BASE = 3,
	DEFAULT_PRIORITY_ROCKET_SITE = 3,
	DEFAULT_PRIORITY_GUN_EMPLACEMENT = 3,
	DEFAULT_PRIORITY_FACILITY = 3,
	DEFAULT_PRIORITY_NAVAL_BASE = 3,
	DEFAULT_PRIORITY_NAVAL_COMBAT = 20,
	DEFAULT_PRIORITY_NAVAL_COMBAT_RESULTS = 19,
	DEFAULT_PRIORITY_LAND_COMBAT = 20,
	DEFAULT_PRIORITY_NAVAL_MISSION = 13,
	DEFAULT_PRIORITY_AIR_MISSION = 13,
	DEFAULT_PRIORITY_SUPPLY = 14,
	DEFAULT_PRIORITY_CAPITAL = 5,
	DEFAULT_PRIORITY_PEACE_COST = 3,
	DEFAULT_PRIORITY_ADJACENCY_RULE = 3,
	DEFAULT_PRIORITY_NAVAL_MINES = 13,
	DEFAULT_PRIORITY_NAVAL_ACCIDENTS = 13,
	DEFAULT_PRIORITY_NAVAL_ACCIDENTS = 13,  -- Duplicate, left as-is

	STATES_PRIORITY_UNITS_STACK = 10,
	STATES_PRIORITY_UNITS_STACK_GROUP = 11,
	STATES_PRIORITY_VICTORY_POINTS = 5,
	STATES_PRIORITY_RESOURCE = 10,
	STATES_PRIORITY_CONSTRUCTION_INFO = 3,
	STATES_PRIORITY_AIR_BASE = 3,
	STATES_PRIORITY_ROCKET_SITE = 3,
	STATES_PRIORITY_GUN_EMPLACEMENT = 3,
	STATES_PRIORITY_FACILITY = 3,
	STATES_PRIORITY_NAVAL_BASE = 3,
	STATES_PRIORITY_NAVAL_COMBAT = 20,
	STATES_PRIORITY_NAVAL_COMBAT_RESULTS = 19,
	STATES_PRIORITY_LAND_COMBAT = 20,
	STATES_PRIORITY_NAVAL_MISSION = 13,
	STATES_PRIORITY_AIR_MISSION = 13,
	STATES_PRIORITY_SUPPLY = 14,
	STATES_PRIORITY_CAPITAL = 5,
	STATES_PRIORITY_PEACE_COST = 3,
	STATES_PRIORITY_ADJACENCY_RULE = 3,
	STATES_PRIORITY_NAVAL_MINES = 13,
	STATES_PRIORITY_NAVAL_ACCIDENTS = 13,

	SUPPLY_AREAS_PRIORITY_UNITS_STACK = 10,
	SUPPLY_AREAS_PRIORITY_UNITS_STACK_GROUP = 11,
	SUPPLY_AREAS_PRIORITY_VICTORY_POINTS = 5,
	SUPPLY_AREAS_PRIORITY_RESOURCE = 10,
	SUPPLY_AREAS_PRIORITY_CONSTRUCTION_INFO = 3,
	SUPPLY_AREAS_PRIORITY_AIR_BASE = 3,
	SUPPLY_AREAS_PRIORITY_ROCKET_SITE = 3,
	SUPPLY_AREAS_PRIORITY_GUN_EMPLACEMENT = 3,
	SUPPLY_AREAS_PRIORITY_FACILITY = 3,
	SUPPLY_AREAS_PRIORITY_NAVAL_BASE = 3,
	SUPPLY_AREAS_PRIORITY_NAVAL_COMBAT = 20,
	SUPPLY_AREAS_PRIORITY_NAVAL_COMBAT_RESULTS = 19,
	SUPPLY_AREAS_PRIORITY_LAND_COMBAT = 20,
	SUPPLY_AREAS_PRIORITY_NAVAL_MISSION = 13,
	SUPPLY_AREAS_PRIORITY_AIR_MISSION = 13,
	SUPPLY_AREAS_PRIORITY_SUPPLY = 14,
	SUPPLY_AREAS_PRIORITY_CAPITAL = 5,
	SUPPLY_AREAS_PRIORITY_PEACE_COST = 3,
	SUPPLY_AREAS_PRIORITY_ADJACENCY_RULE = 3,
	SUPPLY_AREAS_PRIORITY_NAVAL_MINES = 13,
	SUPPLY_AREAS_PRIORITY_NAVAL_ACCIDENTS = 13,

	STRATEGIC_AIR_PRIORITY_UNITS_STACK = 10,
	STRATEGIC_AIR_PRIORITY_UNITS_STACK_GROUP = 11,
	STRATEGIC_AIR_PRIORITY_VICTORY_POINTS = 5,
	STRATEGIC_AIR_PRIORITY_RESOURCE = 10,
	STRATEGIC_AIR_PRIORITY_CONSTRUCTION_INFO = 3,
	STRATEGIC_AIR_PRIORITY_AIR_BASE = 30,
	STRATEGIC_AIR_PRIORITY_ROCKET_SITE = 3,
	STRATEGIC_AIR_PRIORITY_GUN_EMPLACEMENT = 3,
	STRATEGIC_AIR_PRIORITY_FACILITY = 3,
	STRATEGIC_AIR_PRIORITY_NAVAL_BASE = 3,
	STRATEGIC_AIR_PRIORITY_NAVAL_COMBAT = 20,
	STRATEGIC_AIR_PRIORITY_NAVAL_COMBAT_RESULTS = 19,
	STRATEGIC_AIR_PRIORITY_LAND_COMBAT = 20,
	STRATEGIC_AIR_PRIORITY_NAVAL_MISSION = 13,
	STRATEGIC_AIR_PRIORITY_AIR_MISSION = 290,  -- Modified by mod
	STRATEGIC_AIR_PRIORITY_SUPPLY = 14,
	STRATEGIC_AIR_PRIORITY_CAPITAL = 5,
	STRATEGIC_AIR_PRIORITY_PEACE_COST = 3,
	STRATEGIC_AIR_PRIORITY_ADJACENCY_RULE = 3,
	STRATEGIC_AIR_PRIORITY_NAVAL_MINES = 13,
	STRATEGIC_AIR_PRIORITY_NAVAL_ACCIDENTS = 13,

	-- [Other sections follow same structure with mod changes applied] --
	-- Full implementation would continue here with all keys --
},

NAirGfx = {
	AIRPLANES_ANIMATION_GLOBAL_SPEED_PER_GAMESPEED = {0.1, 0.1, 0.1, 0.1, 0.1, 0.1},  -- Modified by mod
	ROCKET_SPEED = 15.0,							
	AIRPLANES_CURVE_POINT_DENSITY = 2.0, 			
	AIRPLANES_CURVE_MAX_EXTRAPOLATION = 20.0, 		
	AIRPLANES_CURVE_MIN_ELEVATION = 4.0, 			
	AIRPLANES_SCALE_TAKEOFF_DIST = 0.1, 				
	AIRPLANES_SCALE_MIN = 0.1, 						
	AIRPLANES_SCALE_LANDING_DIST = 0.9, 				
	AIRPLANES_SMOOTH_INTERPOLATION_MOVE = 0.02, 	-- Modified by mod
	AIRPLANES_SMOOTH_INTERPOLATION_TURN = 0.02, 	-- Modified by mod
	AIRPLANES_BANK_STRENGTH = 210.0, 				
	AIRPLANES_BANK_ANGLE_LIMIT = 55.0, 				
	AIRPLANES_GROUND_COLLISION_OFFSET_Y = 0.0, 		
	AIRPLANES_GROUND_EXPLOSION_TIME_DELAY = 0.6,	
	AIRPLANES_1_FIGHTER_PATROL_ANIM = 1, 			
	AIRPLANES_3_FIGHTER_PATROL_ANIM = 3,			
	AIRPLANES_1_BOMBER_BOMBING_ANIM = 1, 			
	AIRPLANES_3_BOMBER_BOMBING_ANIM = 3, 			
	AIRPLANES_1_FIGHTER_VS_1_FIGHTER_ANIM = 1, 		
	AIRPLANES_3_FIGHTER_VS_3_FIGHTER_ANIM = 3,		
	AIRPLANES_1_TRANSPORT_SUPPLY_ANIM = 1,			
	AIRPLANES_3_TRANSPORT_SUPPLY_ANIM = 3,			
	AIRPLANES_1_SCOUT_PLANE_PATROL_ANIM = 1,
	AIRPLANES_3_SCOUT_PLANE_PATROL_ANIM = 3,

	RANDOM_SCENARIO_ANIMATION_MAX_DELAY = 3.0,		
	STRAT_BOMBER_FIREBOMB_THRESHOLD = 42.0,         
	STRAT_BOMBER_CARPETBOMB_THRESHOLD = 16.0,       
	BOMBERS_DIVISION_FACTOR = 30,					
	MISSILES_DIVISION_FACTOR = 60,					
	FIGHTERS_DIVISION_FACTOR = 30,					
	SCOUT_PLANE_DIVISION_FACTOR = 30,				
	TRANSPORT_DIVISION_FACTOR = 30,
	MAX_MISSILE_BOMBING_SCENARIOS = 0,  -- Modified by mod				
	MAX_PATROL_SCENARIOS = 0,  -- Modified by mod					
	MAX_BOMBING_SCENARIOS = 0,  -- Modified by mod					
	MAX_DOGFIGHTS_SCENARIOS = 0,  -- Modified by mod					
	MAX_TRANSPORT_SCENARIOS = 0,  -- Modified by mod
	MAX_TRAINING_SCENARIOS = 2,						
	MAX_SCOUT_SCENARIOS = 2,
},

NGraphics = {
	COUNTER_MODE_ALLEGIANCE_OURS = { 0.32, 0.71, 0.39, 1.0 },
	COUNTER_MODE_ALLEGIANCE_ALLIED = { 0.31, 0.65, 0.94, 1.0 },
	COUNTER_MODE_ALLEGIANCE_ENEMY = { 0.91, 0.30, 0.30, 1.0 },
	COUNTER_MODE_ALLEGIANCE_OTHER = { 0.8, 0.8, 0.8, 1.0 },

	MAX_NUMBER_OF_TEXTURES = 10000, 

	MIN_TRAIN_WAGON_COUNT = 1,  -- Modified by mod
	MAX_TRAIN_WAGON_COUNT = 1,  -- Modified by mod
	RAILWAY_BRIDGE_ENTITY = "bridge_railway_entity",
	RAILWAY_BRIDGE_LARGE_ENTITY = "bridge_railway_large_entity",
	RAILWAY_Y_OFFSET = 0.9,  -- Modified by mod
	RAILWAY_BRIDGE_Y_OFFSET = 0.6,  -- Modified by mod
	RAILWAY_BRIDGE_WIDTH = 0,  -- Modified by mod
	RAILWAY_BRIDGE_LARGE_WIDTH = 0,  -- Modified by mod
	RAILWAY_BRIDGE_GAP_WIDTH = 0,  -- Modified by mod
	RAILWAY_BRIDGE_GAP_LARGE_WIDTH = 0,  -- Modified by mod
	TRAIN_MAP_SPEED = 3.0,							
	TUNNELBANA_TIMETABLE = { 9200, 12000 },			

	MAX_MESHES_LOADED_PER_FRAME = 50,  -- Modified by mod
	MESH_POPUP_SCALE_UP_SPEED = 5.0,
	MESH_POPUP_SCALE_DOWN_SPEED = 2.1,
	SHIP_POPUP_SCALE_DOWN_SPEED = 4.1,
	PORT_SHIP_OFFSET = 2.0,
	SHIP_IN_PORT_SCALE = 0.25,
	MAP_BUILDINGS_SHRINK_DISTANCE = 180,
	MAP_BUILDINGS_DESTROYED_STATUS = 60,			
	MAP_BUILDINGS_DESTROYED_DEAD_ZONE = 80,			
	MAP_BUILDINGS_DAMAGED_THRESHOLD = 0.80,			
	CITY_DAMAGED_THRESHOLD = 0.80,					
	CITY_DESTROYED_THRESHOLD = 0.30,				
	CITY_SPRAWL_SHRINK_DISTANCE = 0,  -- Modified by mod
	DRAW_MAP_OBJECTS_CUTOFF = 300,  -- Modified by mod
	PROVINCE_NAME_DRAW_DISTANCE = 350,  -- Modified by mod
	DIRECTION_POINTER_DRAW_DISTANCE = 1200.0,		
	DIRECTION_POINTER_INTERPOLATION_SPEED = 0.275,	
	DIRECTION_POINTER_SCREEN_AREA_MAX = 0.935, 		
	DIRECTION_POINTER_SCREEN_AREA_MIN = 0.910,		
	DIRECTION_POINTER_SIZE_MIN = 0.9,				
	DIRECTION_POINTER_SIZE_MAX = 10.0,
	DIRECTION_POINTER_GROUND_OFFSET = 5.0,			
	LIGHT_DIRECTION_X = -1.0,
	LIGHT_DIRECTION_Y = -1.0,
	LIGHT_DIRECTION_Z = 0.5,
	LIGHT_SHADOW_DIRECTION_X = -5.0,
	LIGHT_SHADOW_DIRECTION_Y = -8.0,
	LIGHT_SHADOW_DIRECTION_Z = 5.0,
	LIGHT_HDR_RANGE = 1.0,
	BORDER_WIDTH = 1.4,  -- Modified by mod
	PROVINCE_BORDER_FADE_NEAR = 250,  -- Modified by mod
	PROVINCE_BORDER_FADE_FAR = 350,  -- Modified by mod
	STATE_BORDER_FADE_NEAR = 450,  -- Modified by mod
	STATE_BORDER_FADE_FAR = 550,  -- Modified by mod
	LAND_UNIT_MOVEMENT_SPEED = 12  ,
	NAVAL_UNIT_MOVEMENT_SPEED = 12,
	ARROW_MOVEMENT_SPEED = 2,
	DRAW_COUNTRY_NAMES_CUTOFF = 500,  -- Modified by mod
	TRADEROUTE_SMOOTHNESS = 0.65,
	TRADEROUTE_SMOOTHEN_PASSES = 2,
	SUPPLYFLOW_SMOOTHNESS = 0.25,
	SUPPLYFLOW_SMOOTHEN_PASSES = 2,
	SNAPPED_OFF_FRONT_SMOOTHNESS = 0.5,
	SNAPPED_OFF_FRONT_SMOOTHEN_PASSES = 2,
	ROOT_FRONT_SMOOTHNESS = 0.5,
	ROOT_FRONT_SMOOTHEN_PASSES = 1,
	ROOT_FRONT_OFFSET = 2,  -- Modified by mod
	ROOT_FRONT_MAX_INTERSECTION_TESTS_FRONT = 30,		
	ROOT_FRONT_MAX_INTERSECTION_TESTS_ORDER = 25,		
	ORDER_FRONT_MAX_OFFSETS = 4,						
	ORDER_FRONT_SMOOTHNESS = 0.5,
	ORDER_FRONT_SMOOTHEN_PASSES = 2,
	ORDER_MOVE_SMOOTHNESS = 0.99,
	ORDER_MOVE_SMOOTHEN_PASSES = 2,
	UNIT_TURN_SPEED = 3,
	BORDER_COLOR_SELECTION_STATE_R = 1.0,
	BORDER_COLOR_SELECTION_STATE_G = 0.62,
	BORDER_COLOR_SELECTION_STATE_B = 0.33,
	BORDER_COLOR_SELECTION_STATE_A = 1.0,
	BORDER_COLOR_SELECTION_SUPPLY_AREA_R = 0.6,
	BORDER_COLOR_SELECTION_SUPPLY_AREA_G = 0.2,
	BORDER_COLOR_SELECTION_SUPPLY_AREA_B = 0.6,
	BORDER_COLOR_SELECTION_SUPPLY_AREA_A = 1.0,
	BORDER_COLOR_SELECTION_ADJACENCY_RULE_AREA_R = 0.0,
	BORDER_COLOR_SELECTION_ADJACENCY_RULE_AREA_G = 1.0,
	BORDER_COLOR_SELECTION_ADJACENCY_RULE_AREA_B = 1.0,
	BORDER_COLOR_SELECTION_ADJACENCY_RULE_AREA_A = 1.0,
	BORDER_COLOR_SELECTION_BUILDING_AREA_R = 1.0,
	BORDER_COLOR_SELECTION_BUILDING_AREA_G = 1.0,
	BORDER_COLOR_SELECTION_BUILDING_AREA_B = 1.0,
	BORDER_COLOR_SELECTION_BUILDING_AREA_A = 1.0,
	BORDER_COLOR_SELECTION_PROVINCE_R = 1.0,
	BORDER_COLOR_SELECTION_PROVINCE_G = 0.8,
	BORDER_COLOR_SELECTION_PROVINCE_B = 0.0,
	BORDER_COLOR_SELECTION_PROVINCE_A = 1.0,
	BORDER_COLOR_CUSTOM_HIGHLIGHTS = {
		0.0, 0.61, 0.75, 1.0, 
		1.0, 0.06, 0.0, 1.0,  
		0.1, 0.6, 0.2, 1.0,   
		0.8, 0.3, 0.0, 1.0,   
		0.0, 0.4, 0.8, 1.0,   
		0.3, 0.9, 0.3, 0.8,   
		0.7, 0.7, 0.0, 1.0,   
		0.1, 0.6, 0.2, 1.0,   
		1.0, 0.06, 0.0, 1.0,  
		0.3, 0.9, 0.3, 0.8,   
		0.0, 0.4, 0.8, 1.0,   
		0.8, 0.3, 0.0, 1.0,   
		0.7, 0.7, 0.0, 1.0,   
	},

	BORDER_COLOR_TUTORIAL_HIGHLIGHT_R = 0.0,
	BORDER_COLOR_TUTORIAL_HIGHLIGHT_G = 0.61,
	BORDER_COLOR_TUTORIAL_HIGHLIGHT_B = 0.75,
	BORDER_COLOR_TUTORIAL_HIGHLIGHT_A = 1.0,
	BORDER_COLOR_DEMILITARIZED_R = 1.0,
	BORDER_COLOR_DEMILITARIZED_G = 0.06,
	BORDER_COLOR_DEMILITARIZED_B = 0.0,
	BORDER_COLOR_DEMILITARIZED_A = 0.9,
	BORDER_COLOR_BORDER_CONFLICT_EDGE_R = 1.0,
	BORDER_COLOR_BORDER_CONFLICT_EDGE_G = 0.2,
	BORDER_COLOR_BORDER_CONFLICT_EDGE_B = 0.0,
	BORDER_COLOR_BORDER_CONFLICT_EDGE_A = 1.0,
	BORDER_COLOR_BORDER_CONFLICT_NON_EDGE_R = 0.7,
	BORDER_COLOR_BORDER_CONFLICT_NON_EDGE_G = 1.0,
	BORDER_COLOR_BORDER_CONFLICT_NON_EDGE_B = 0.0,
	BORDER_COLOR_BORDER_CONFLICT_NON_EDGE_A = 0.9,
	DRAW_REFRACTIONS_CUTOFF = 0,  -- Modified by mod
	DRAW_SHADOWS_CUTOFF = 0,  -- Modified by mod
	DRAW_SHADOWS_FADE_LENGTH = 0,  -- Modified by mod
	DRAW_FOW_CUTOFF = 0,  -- Modified by mod
	DRAW_FOW_FADE_LENGTH = 0,  -- Modified by mod
	GRADIENT_BORDERS_FIELD_COUNTRY_REFRESH = 1,  -- Modified by mod
	GRADIENT_BORDERS_FIELD_COUNTRY_LOW = 300.0, 
	GRADIENT_BORDERS_FIELD_COUNTRY_HIGH = 9000.0, 
	GRADIENT_BORDERS_THICKNESS_COUNTRY_LOW = 5.0, 
	GRADIENT_BORDERS_COUNTRY_CENTER_THICKNESS = 2.0, 
	GRADIENT_BORDERS_THICKNESS_COUNTRY_HIGH = 25.0,
	GRADIENT_BORDERS_THICKNESS_STATE = 5.0,
	GRADIENT_BORDERS_THICKNESS_RESISTANCE = 5.0,
	GRADIENT_BORDERS_THICKNESS_INTEL_LEDGER = 5.0,
	GRADIENT_BORDERS_THICKNESS_SUPPLY_AREA_A = 250,  -- Modified by mod
	GRADIENT_BORDERS_THICKNESS_SUPPLY_AREA_B = 250,  -- Modified by mod
	GRADIENT_BORDERS_THICKNESS_STRATEGIC_REGIONS = 250.0,  -- Modified by mod
	GRADIENT_BORDERS_THICKNESS_DIPLOMACY = 12.0,
	GRADIENT_BORDERS_THICKNESS_DIPLOMACY_ON_INTEL_LEDGER = 3.0,
	GRADIENT_BORDERS_THICKNESS_PEACE_CONFERENCE_A = 3.0, 
	GRADIENT_BORDERS_THICKNESS_PEACE_CONFERENCE_B = 6.0, 
	GRADIENT_BORDERS_OUTLINE_CUTOFF_COUNTRY = 0.973, 
	GRADIENT_BORDERS_OUTLINE_CUTOFF_DIPLOMACY = 0.973,
	GRADIENT_BORDERS_OUTLINE_CUTOFF_DIPLOMACY_ON_INTEL_LEDGER = 0.973,
	GRADIENT_BORDERS_OUTLINE_CUTOFF_STATE = 0.973,
	GRADIENT_BORDERS_OUTLINE_CUTOFF_SUPPLY_AREA = 0.973,
	GRADIENT_BORDERS_OUTLINE_CUTOFF_STRATEGIC_REGIONS = 0.98,
	GRADIENT_BORDERS_OUTLINE_CUTOFF_RESISTANCE = 0.973,
	GRADIENT_BORDERS_OUTLINE_CUTOFF_FACTIONS = 0.973,
	GRADIENT_BORDERS_OUTLINE_CUTOFF_INTEL_LEDGER = 0.973,
	GRADIENT_BORDERS_OUTLINE_CUTOFF_PEACE_CONFERENCE = 0.973,
	GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_COUNTRY = 0.0, 
	GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_STATE = 0.4,
	GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_SUPPLY_AREA = 1.0,
	GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_STRATEGIC_REGIONS = 1.0,
	GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_RESISTANCE = 0.35,
	GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_FACTIONS = 0.0,
	GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_TERRAIN = 0.39,
	GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_INTEL_LEDGER = 0.2,
	GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_DIPLOMACY = 0.0,
	GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_DIPLOMACY_ON_INTEL_LEDGER = 1.0,
	GRADIENT_BORDERS_CAMERA_DISTANCE_OVERRIDE_PEACE_CONFERENCE = 1.0,
	GRADIENT_BORDERS_ACTIVATE_FOR_PEACE_CONFERENCE = false,
	GRADIENT_BORDERS_ONE_COLOR_FOR_PEACE_CONFERENCE = { -1.0, -1.0, -1.0, -1.0 }, 

	GRADIENT_BORDERS_OPTIMIZATION_RANGE = 30.0, 
	GRADIENT_BORDERS_REFRESH_FREQ = 0.2,  -- Modified by mod
	STRATEGIC_AIR_COLOR_BAD = {0.65, 0, 0, 1},  -- Modified by mod
	STRATEGIC_AIR_COLOR_GOOD = {0, 0.65, 0, 1},  -- Modified by mod
	STRATEGIC_AIR_COLOR_AVERAGE = {0.65, 0.65, 0, 1},  -- Modified by mod
	STRATEGIC_AIR_COLOR_NEUTRAL = {130.0/255, 130.0/255, 130.0/255, 1},  -- Modified by mod
	STRATEGIC_AIR_COLOR_GOOD_WHILE_HIGHLIGHTING_HOLD = {0, 0.8, 0, 1},
	STRATEGIC_AIR_COLOR_AVERAGE_WHILE_HIGHLIGHTING_HOLD = {0.8, 0.8, 0, 1},
	STRATEGIC_AIR_COLOR_NEUTRAL_WHILE_HIGHLIGHTING_HOLD = {140.0/255, 131.0/255, 119.0/255, 1},

	STRATEGIC_NAVY_COLOR_NEUTRAL = {130.0/255, 130.0/255, 130.0/255, 1},  -- Modified by mod
	STRATEGIC_NAVY_COLOR_ON_HOLD = {0.2, 0.5, 0.6, 0.5},	
	STRATEGIC_NAVY_COLOR_ON_HOLD_HIGHLIGHTED = {0.2, 0.6, 0.7, 0.5},	
	STRATEGIC_NAVY_COLOR_BAD = {0.8, 0, 0, 1},  
	STRATEGIC_NAVY_COLOR_GOOD = {0, 0.8, 0, 1}, 
	STRATEGIC_NAVY_COLOR_AVERAGE = {0.8, 0.8, 0, 1}, 
	STRATEGIC_NAVY_NO_TASKFORCES_ASSIGNED = {0.9, 0.3, 0.3, 1},  
	STRATEGIC_NAVY_COLOR_BAD_WHILE_HIGHLIGHTING_HOLD = {0.7, 0.0, 0.40, 0.5}, 	
	STRATEGIC_NAVY_COLOR_GOOD_WHILE_HIGHLIGHTING_HOLD = {0, 0.6, 0.5, 1},		
	STRATEGIC_NAVY_COLOR_AVERAGE_WHILE_HIGHLIGHTING_HOLD = {0.5, 0.5, 0.6, 1},	

	RESISTANCE_COLOR_NONE = {0.4, 0.4, 0.6, 0.5}, 
	RESISTANCE_COLOR_GOOD = {0.0, 0.65, 0, 1},  -- Modified by mod
	RESISTANCE_COLOR_AVERAGE = {0.65, 0.65, 0, 1},  -- Modified by mod
	RESISTANCE_COLOR_BAD = {0.65, 0, 0, 1},  -- Modified by mod
	CONSTRUCTION_CONVERSION_COLOR = { 0.9, 0.9, 0.3, 0.1},
	CONSTRUCTION_CONVERSION_IN_PROGRESS_COLOR = { 0.3, 0.3, 0.9, 0.1},
	VIRTUAL_BATTLEPLANS_COLOR = { 0.2, 1.0, 0.2, 1 },
	ALLIED_BATTLEPLANS_COLOR = { 0.3, 0.4, 1.0, 1 },
	OFFENSIVE_PING_CIRCLE_COLOR = { 0.64, 0.48, 0.35 },
	DEFENSIVE_PING_CIRCLE_COLOR = { 0.4, 0.55, 0.66 },
	GMT_OFFSET = 2793, 
	DAY_NIGHT_FEATHER = 0.024,  -- Modified by mod
	SOUTH_POLE_OFFSET = 0.17, 
	NORTH_POLE_OFFSET = 0.93,
	COUNTRY_FLAG_TEX_WIDTH = 82, 
	COUNTRY_FLAG_TEX_HEIGHT = 52,
	COUNTRY_FLAG_TEX_MAX_SIZE = 256, 
	COUNTRY_FLAG_MEDIUM_TEX_WIDTH = 41,
	COUNTRY_FLAG_MEDIUM_TEX_HEIGHT = 26,
	COUNTRY_FLAG_MEDIUM_TEX_MAX_SIZE = 1024, 
	COUNTRY_FLAG_SMALL_TEX_WIDTH = 10,
	COUNTRY_FLAG_SMALL_TEX_HEIGHT = 7,
	COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 256, 
	VICTORY_POINT_LEVELS = 3,
	VICTORY_POINT_MAP_ICON_AFTER = {0, 9, 20}, 
	VICTORY_POINT_MAP_ICON_CAPITAL_CUTOFF_MAX = 1000.0,	
	VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {300, 500, 1500},  -- Modified by mod
	VICTORY_POINT_MAP_ICON_TEXT_CUTOFF_MIN = 100.0, 
	VICTORY_POINT_MAP_ICON_TEXT_CUTOFF_MAX = 800.0, 
	VICTORY_POINT_MAP_ICON_DOT_CUTOFF_MIN = 100.0, 
	VICTORY_POINT_MAP_ICON_DOT_CUTOFF_MAX = 1000.0, 
	VICTORY_POINT_MAP_ICON_MAX_VICTORY_POINTS_FOR_PERCENT = 22, 
	AIRBASE_ICON_DISTANCE_CUTOFF = 900,  -- Modified by mod
	NAVALBASE_ICON_DISTANCE_CUTOFF = 900,  -- Modified by mod
	RADAR_ICON_DISTANCE_CUTOFF = 499,  -- Modified by mod
	RESOURCE_MAP_ICON_TEXT_CUTOFF = 800,  
	RESISTANCE_MAP_ICON_MODIFIERS_DISTANCE_CUTOFF = 500,  
	RESISTANCE_MAP_ICON_DISTANCE_CUTOFF = 1200,  
	PROVINCE_ANIM_TEXT_DISTANCE_CUTOFF = 200,  -- Modified by mod
	CAPITAL_ICON_CUTOFF = 1100,	
	UNITS_DISTANCE_CUTOFF = 350,  -- Modified by mod
	SHIPS_DISTANCE_CUTOFF = 50,  -- Modified by mod
	UNIT_ARROW_DISTANCE_CUTOFF = 500,  -- Modified by mod
	UNITS_ICONS_DISTANCE_CUTOFF = 400,  -- Modified by mod
	NAVAL_COMBAT_DISTANCE_CUTOFF = 999,  -- Modified by mod
	FACILITY_DISTANCE_CUTOFF = 900, 
	ADJACENCY_RULE_DISTANCE_CUTOFF = 1000,  -- Modified by mod
	LAND_COMBAT_DISTANCE_CUTOFF = 700,  -- Modified by mod
	PROV_CONSTRUCTION_ICON_DISTANCE_CUTOFF = 300,  -- Modified by mod
	STATE_CONSTRUCTION_ICON_DISTANCE_CUTOFF = 1000,  -- Modified by mod
	DECISION_MAP_ICON_DISTANCE_CUTOFF = 1000,  -- Modified by mod
	DECISION_MAP_ICON_DEPTH_PRIORITY = 50,
	NAVAL_MISSION_TASK_FORCES_GROUP_BY_ALLEGIANCE_CUTOFF = 500,
	NAVAL_MISSION_ICONS_DISTANCE_CUTOFF = 900, 
	NAVAL_MINES_DISTANCE_CUTOFF = 800,
	CRYPTOLOGY_MAP_ICON_DISTANCE_CUTOFF = 1000,
	PEACE_CONFERENCE_MAP_ICON_DISTANCE_CUTOFF = 500,
	NAVAL_MINES_CLUMPING = 58, 
	NAVAL_MINES_CLUMP_NEAR_TERRITORY = 25, 
	NAVAL_MINES_COUNT_TO_VISUAL_ASPECT = 0.1, 
	MAP_ICONS_GROUP_CAM_DISTANCE = 100,  -- Modified by mod
	MAP_ICONS_STATE_GROUP_CAM_DISTANCE = 450,  -- Modified by mod
	MAP_ICONS_STRATEGIC_GROUP_CAM_DISTANCE = 700,  -- Modified by mod
	MAP_ICONS_STRATEGIC_AREA_HUGE = 220,  -- Modified by mod
	MAP_ICONS_STATE_HUGE = 100,  -- Modified by mod
	MAPICON_GROUP_STRATEGIC_SIZE = 1000,  -- Modified by mod
	MAP_ICONS_GROUP_SPLIT_SELECTED_LIMIT = 10,  -- Modified by mod
	MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE = 125,  -- Modified by mod
	MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE_STRATEGIC = 350,  -- Modified by mod
	MAPICON_GROUP_PASSES = 5,  -- Modified by mod
	MAP_ICONS_GROUP_SPLIT_SELECTED_LIMIT = 12,   
	MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE = 250, 
	MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE_STRATEGIC = 0, 
	RIVER_FADE_FROM = 20.0, 
	RIVER_FADE_TO = 3.0,
	TOOLTIP_DELAYED_DELAY = 1, 						
	TOOLTIP_SHOW_DELAY = 0.05, 						
	TOOLTIP_HIDE_DELAY = 0.05, 						

	INTEL_LEDGER_CIVILIAN_ICON_STATE_CUTOFF = 250.0,
	INTEL_LEDGER_CIVILIAN_ICON_REGION_CUTOFF = 700.0,

	RAILWAY_CAMERA_CUTOFF = 300.0,  -- Modified by mod
	RAILWAY_CAMERA_CUTOFF_SPEED = 3.0, 

	DIVISION_NAMES_GROUP_MAX_TOOLTIP_ENTRIES = 15,	
	NAMES_GROUP_MAX_NAME_LIST_ENTRIES = 25,	

	WEATHER_DISTANCE_CUTOFF = 0,  -- Modified by mod
	WEATHER_DISTANCE_FADE_LENGTH = 400,  -- Modified by mod
	WEATHER_ZOOM_IN_CUTOFF = 1,  -- Modified by mod
	WEATHER_ZOOM_IN_FADE_LENGTH = 220,  -- Modified by mod
	WEATHER_ZOOM_IN_FADE_FACTOR = 0.0,  -- Modified by mod
	WEATHER_PLAYBACK_RATE = 0.25,  -- Modified by mod
	WEATHER_PLAYBACK_RATE_CUTOFF = 400,  -- Modified by mod
	WEATHER_PLAYBACK_RATE_LENGTH = 200,  -- Modified by mod
	WEATHER_ZOOM_IN_CUTOFF = 358, 
	WEATHER_ZOOM_IN_FADE_LENGTH = 220, 
	WEATHER_ZOOM_IN_FADE_FACTOR = 0.0, 
	WEATHER_PLAYBACK_RATE = 0.15, 
	WEATHER_PLAYBACK_RATE_CUTOFF = 500, 
	WEATHER_PLAYBACK_RATE_LENGTH = 200, 

	POSTEFFECT_PER_PROVINCE_MIN_SNOW = 0.1,
	POSTEFFECT_PER_PROVINCE_MAX_SNOW = 0.2,
	POSTEFFECT_TOTAL_MIN_SNOW = 0.0,
	POSTEFFECT_TOTAL_MAX_SNOW = 0.05,
	POSTEFFECT_FEATHER_MIN_DISTANCE = 300.0,
	POSTEFFECT_FEATHER_MAX_DISTANCE = 2000.0,
	POSTEFFECT_FEATHER_AT_MIN = 0.03,
	POSTEFFECT_FEATHER_AT_MAX = 0.80,

	LAND_COMBAT_BALANCED_COLOR = { 1.0, 1.0, 0.0, 1.0 },
	LAND_COMBAT_LOSING_COLOR = { 1.0, 0.0, 0.0, 1.0 },
	LAND_COMBAT_WINNING_COLOR = { 0.0, 1.0, 0.0, 1.0 },

	BLOOM_WIDTH = 0,  -- Modified by mod
	BLOOM_SCALE = 0,  -- Modified by mod
	BRIGHT_THRESHOLD = 0,  -- Modified by mod
	EMISSIVE_BLOOM_STRENGTH = 0,  -- Modified by mod
	MIN_HDR_ADJUSTMENT = 0.5,     
	MAX_HDR_ADJUSTMENT = 1.0,      
	HDR_ADJUSTMENT_SPEED = 15.0, 
	TONE_MAP_MIDDLE_GREY = 0.5, 
	TONE_MAP_LUMINANCE_WHITE = 1.0, 
	MOON_HEIGHT = 600, 
	SUN_HEIGHT  = 600, 
	MOON_HEIGHT_WATER = 550,   
	SUN_HEIGHT_WATER  = 5000,  
	MOON_LATITUDE = 0, 
	SUN_LATITUDE  = 848,
	SECOND_MOON_LATITUDE = 100, 
	SECOND_SUN_LATITUDE = 100,

	AMBIENT_LIGHT_POS_X = { 0.2,  0.2, 0.2 }, 
	AMBIENT_LIGHT_NEG_X = { 0.4,  0.1, 0.6 }, 
	AMBIENT_LIGHT_POS_Y = { 0.0,  0.0, 0.0 },
	AMBIENT_LIGHT_NEG_Y = { 0.35, 0.2, 0.0 },
	AMBIENT_LIGHT_POS_Z = { 0.6,  0.2, 0.924 }, 
	AMBIENT_LIGHT_NEG_Z = { 0.55, 0.1, 0.9 }, 

	SUN_DIFFUSE_COLOR   	= {0.14, 0.0, 1.0},
	SUN_INTENSITY 			= 1.0; 
	SUN_SPECULAR_INTENSITY 	= 1.0;
	MOON_DIFFUSE_COLOR  	= {0.58, 0.5, 1.0},
	MOON_INTENSITY 			= 2.5;

	CUBEMAP_INTENSITY = 1.0,

	TREE_FADE_NEAR = 0,  -- Modified by mod
	TREE_FADE_FAR = 0,  -- Modified by mod

	TRADE_ROUTE_NUM_CONVOYS_SCALE_FACTOR = 0.3,
	TRADE_ROUTE_MAX_NUM_CONVOYS = 4,
	TRADE_ROUTE_CONVOY_SPEED = 0.6,
	TRADE_ROUTE_CONVOY_SLEEP_TIME = 3.0,
	TRADE_ROUTE_CONVOY_ROUTE_OFFSET = 0.5,
	SHIP_IN_MISSION_SPEED = 2.5,
	SHIP_IN_MISSION_TURN_RADIUS = 5.0,
	SHIP_IN_MISSION_TARGET_SIZE = 0.5,
	SHIP_IN_MISSION_SCALE = 0.6,
	TRADE_ROUTE_LINE_OFFSET = 0.5,
	TRADE_ROUTE_MAX_LINES = 6,
	TRADE_ROUTE_BAD_EFFICIENCY_THRESHOLD = 0.8,
	TRADE_ROUTE_REGIONAL_BAD_EFFICIENCY_THRESHOLD = 0.9,
	TRADE_ROUTE_BAD_EFFICIENCY_ROUTE_COLOR = { 1.0, 0.7, 0.5, 0.75 },
	TRADE_ROUTE_BAD_EFFICIENCY_HOTSPOT_COLOR = { 1.0, 0.0, 0.0, 0.75 },
	TRADE_ROUTE_PRODUCTION_TRANSFER_COLOR = { 0.0, 0.5, 1.0, 0.75 },
	TRADE_ROUTE_SUPPLIES_TRANSFER_COLOR = { 1.0, 1.0, 1.0, 0.75 },
	TRADE_ROUTE_RESOURCE_EXPORT_COLOR = { 0.7, 1.0, 0.5, 0.75 },
	TRADE_ROUTE_RESOURCE_IMPORT_COLOR = { 0.2, 0.9, 1.0, 0.75 },
	TRADE_ROUTE_LEND_LEASE_EXPORT_COLOR = { 0.5, 1.0, 0.0, 0.75 },
	TRADE_ROUTE_LEND_LEASE_IMPORT_COLOR = { 0.5, 1.0, 0.0, 0.75 },
	TRADE_ROUTE_INTERNATIONAL_MARKET_COLOR = {0.0, 1.0, 0.0, 0.75},

	TRAIT_GRID_COLUMN_OFFSET = 3,
	TRAIT_GRID_COLUMN_WIDTH = 208,
	TRAIT_GRID_ROW_SHIFT = 48,

	TRAIT_LINE_ASSIGNED_COLOR = { 0.47, 0.93, 0.65 }, 
	TRAIT_LINE_NON_ASSIGNED_COLOR = { 0.67, 0.75, 0.93 }, 
	TRAIT_LINE_HIGHLIGHT_COLOR = { 1.0, 1.0, 0.0 }, 
	TRAIT_INVALID_FOR_ASSIGNMENT_COLOR = { 0.8, 0.3, 0.3 },

	PRIDE_OF_THE_FLEET_MODULATE = { 1.0, 0.95, 0.0, 1.0 }, 

	RAILWAY_MAP_ARROW_THIN_LEVEL_THRESHOLD = 1, 
	RAILWAY_MAP_ARROW_MEDIUM_LEVEL_THRESHOLD = 3, 
	RAILWAY_MAP_ARROW_THICK_LEVEL_THRESHOLD = 5, 

	RAILWAY_MAP_ARROW_COLOR_DEFAULT = { 1.0, 1.0, 1.0, 1.0 }, 
	RAILWAY_MAP_ARROW_COLOR_CONSTRUCTION = { 1.0, 0.80, 0.0, 1.0 }, 
	RAILWAY_MAP_ARROW_COLOR_CONSTRUCTION_VALID = { 0.957, 0.871, 0.51, 1.0 }, 
	RAILWAY_MAP_ARROW_COLOR_CONSTRUCTION_INVALID = { 1.0, 0.0, 0.0, 1.0 }, 
	RAILWAY_MAP_ARROW_COLOR_HIGHLIGHTED = { 0.957, 0.871, 0.51, 1.0 }, 
	RAILWAY_MAP_ARROW_COLOR_HIGHLIGHTED_DAMAGED = { 1.0, 1.0, 0.2, 1.0 }, 
	RAILWAY_MAP_ARROW_COLOR_HIGHLIGHTED_ONCOOLDOWN = { 1.0, 0.2, 1.0, 1.0 }, 
	RAILWAY_MAP_ARROW_COLOR_HIGHLIGHTED_CONSTRUCTION = { 0.957, 0.871, 0.51, 1.0 }, 
	RAILWAY_MAP_ARROW_COLOR_HIGHLIGHTED_BOTTLENECK = { 0.902, 0.38, 0.4, 1.0 }, 
	RAILWAY_MAP_ARROW_COLOR_HIGHLIGHTED_BOTTLENECK_MAXLEVEL = { 0.761, 0.647, 0.812, 1.0 }, 
	RAILWAY_MAP_ARROW_COLOR_DAMAGED = { 0.8, 0.8, 0.0, 1.0 }, 
	RAILWAY_MAP_ARROW_COLOR_ONCOOLDOWN = { 0.5, 0.5, 0.5, 1.0 }, 

	RIVER_SUPPLY_MAP_ARROW_COLOR = { 0.8, 0.8, 1.0, 0.8 },
	FLOWING_RIVER_SUPPLY_MAP_ARROW_COLOR = { 0.8, 0.8, 1.0, 0.8 },

	SUPPLY_TO_CONSUMERS_MAP_ARROW_COLOR = { 1.0, 1.0, 1.0, 1.0 }, 
	SUPPLY_TO_CONSUMERS_MAP_ARROW_TRANSPARENCY = 0.8,

	NODE_FLOW_IN_CURRENT_RANGE_COLOR = { 0.68235, 0.0039, 0.4941, 0.55 }, 
	NODE_FLOW_IN_HALF_RANGE_COLOR = { 0.9686, 0.4078, 0.6314, 0.6 }, 
	NODE_FLOW_IN_FULL_RANGE_COLOR = { 0.9843, 0.7059, 0.7255, 0.4 }, 

	RAILWAY_ICON_SHIFT = { 0.0, 0.0, 0.0 },
	SUPPLY_ICON_SHIFT = { 0.0, 0.0, 0.0 },
	SUPPLY_ICON_SWITCH = 200,
	SUPPLY_ICON_CUTOFF = 900.0,               
	SUPPLY_ICON_UNUSED_CUTOFF = 400.0,        
	SUPPLY_ICON_NUMBERS_CUTOFF = 400.0,       
	SUPPLY_ICON_OK_CUTOFF = 750.0,            
	SUPPLY_ICON_DISCONNECTED_CUTOFF = 500.0,  
	SUPPLY_ICON_END_CUTOFF = 200.0,           
	RAILWAY_ICON_CUTOFF = 900.0,
	SUPPLY_SELECTED_NODE_COLOR = { 0.0, 1.0, 1.0, 1.0 },
	SUPPLY_CAPITAL_COLOR = { 1.0, 0.7, 0.0, 1.0 },
	SUPPLY_NAVAL_NODE_COLOR = { 0.1, 0.6, 0.8, 1.0},
	SUPPLY_LAND_NODE_COLOR = { 0.5, 0.8, 0.5, 1.0 },

	SUPPLY_CONSUMER_ARROW_HEIGHT_TO_LEN = 0.1,
	SUPPLY_CONSUMER_ARROW_HEIGHT_MAX = 4.0,

	SUPPLY_UNIT_COUNTER_SHOW_THRESHOLD = 0.5,  
	SUPPLY_UNIT_COUNTER_LOW_THRESHOLD = 0.35,  
	SUPPLY_UNIT_COUNTER_VERY_LOW_THRESHOLD = 0.2,  

	COUP_GREEN = { 0.0, 1.0, 0.0, 1.0 },
	COUP_RED = { 1.0, 0.0, 0.0, 1.0 },

	FRIEND_COLOR  = {0.7, 0.9, 0.7},
	ENEMY_COLOR   = {1.0, 0.7, 0.7},
	NEUTRAL_COLOR = {1.0, 1.0, 1.0},

	COUNTRY_COLOR_HUE_MODIFIER = 0.0,
	COUNTRY_COLOR_SATURATION_MODIFIER = 0.70,  -- Modified by mod
	COUNTRY_COLOR_BRIGHTNESS_MODIFIER = 0.80,  -- Modified by mod
	COUNTRY_UI_COLOR_HUE_MODIFIER = 0.0,
	COUNTRY_UI_COLOR_SATURATION_MODIFIER = 1.0,
	COUNTRY_UI_COLOR_BRIGHTNESS_MODIFIER = 1.0,

	COMMANDGROUP_PRESET_COLORS_HSV = {  -- Modified by mod
		0.0/360.0, 1.0, 1.0, 
		10.0/360.0, 1.0, 1.0, 
		60.0/360.0, 1.0, 1.0, 
		120.0/360.0, 0.75, 1.0, 
		180.0/360.0, 1.0, 1.0, 
		235.0/360.0, 1.0, 1.0, 
		260.0/360.0, 1.0, 1.0, 
		300.0/360.0, 1.0, 1.0, 
		330.0/360.0, 0.0, 1.0 
	},

	CAMERA_OUTSIDE_MAP_DISTANCE_TOP = 200.0,
	CAMERA_OUTSIDE_MAP_DISTANCE_BOTTOM = 200.0,

	CAMERA_ZOOM_SPEED = 50,
	CAMERA_ZOOM_KEY_SCALE = 0.02,
	CAMERA_ZOOM_SPEED_DISTANCE_MULT = 20.0,  -- Modified by mod

	ORDERS_MOUSE_INTERSECT_DISTANCE_MULT = 2.6, 	
	FRONTS_MOUSE_INTERSECT_DISTANCE_MULT = 6.6, 	
	MOVE_ORDERS_MOUSE_INTERSECT_DISTANCE_MULT = 0.5, 	
	TRADE_ROUTE_INTERSECT_DISTANCE_MULT = 10.0,			
	RAILWAY_INTERSECT_DISTANCE_MULT = 3.0,				

	MINIMUM_PROVINCE_SIZE_IN_PIXELS = 8,			

	NATIONAL_FOCUS_SHINE_DISTANCE_SCALE = 0.03,
	NATIONAL_FOCUS_PULSE_BASE =	10.0,
	NATIONAL_FOCUS_PULSE_RANDOM = 10.0,
	POLITICAL_GRID_SMALL_BOX_LIMIT = 6,              	
	SETUP_SPIRIT_GRID_BOX_LIMIT = 3,					
	POLITICAL_PULSE_BASE =	10.0,
	POLITICAL_PULSE_RANDOM = 10.0,

	STRATEGIC_REGION_ZOOM_HEIGHT = 300.0,				

	ARROW_PARADROP_HEIGHT_TO_LEN = 0.3,
	ARROW_PARADROP_HEIGHT_MAX = 11.0,
	ARROW_MIN_TEXT_POINTS_LIMIT = 10,				
	ARROW_EXT_TEXT_POINTS_LIMIT = 20,				
	ARMY_DEFENSIVE_LINE_BUTTON_SIZE = 0.7,			
	ARMY_GROUP_DEFENSIVE_LINE_BUTTON_SIZE = 0.9,	

	SHOW_FOREIGN_SUPPLY_BELOW = 300.0,				
	SHOW_ONLY_PATH_ABOVE = 500.0,					

	ACCLIMATIZATION_CAMO_SHOW_AT = 0.5,				
	ACCLIMATIZATION_CAMO_SHOW_WHEN_IN_STATE = 0.2,	

	INTEL_NETWORK_VALID_TARGET_STRIPE_COLOR = { 0.1, 0.5, 0.8, 1.0 },	
	INTEL_NETWORK_VALID_COUNTRY_TARGET_STRIPE_COLOR = { 0.1, 0.8, 0.5, 0.5 },	

	OCCUPATION_RESISTANCE_NON_INITIALIZED_COLOR = { 1.0, 1.0, 1.0, 0.05 }, 

	OCCUPATION_RESISTANCE_MAP_MODE_COLORS = {
		0.0, 	0.0, 1.0, 0.0, 0.0,
		0.0, 	1.0, 1.0, 0.0, 0.0,
		1.0,	1.0, 1.0, 0.0, 0.1,
		30.0,	1.0, 1.0, 0.0, 0.3,
		100.0,	1.0, 0.0, 0.0, 0.3,
	},
	OCCUPATION_COMPLIANCE_MAP_MODE_COLORS = {
		0.0, 	0.3, 0.6, 0.6, 0.05,
		0.0,	0.3, 0.7, 1.0, 0.05,
		10.0,	0.3, 0.7, 1.0, 0.2,
		50.0,	0.3, 0.7, 1.0, 0.3,
		100.0,	0.3, 0.9, 1.0, 0.5,
	},

	INTEL_LEDGER_ARMY_FORT_LEVEL_COLORS = {
		0.0, 	0.3, 0.3, 0.3, 0.2,
		0.0,	0.7, 0.7, 0.2, 0.3,
		1.0,	0.7, 0.2, 0.2, 0.5,
	},

	INTEL_LEDGER_NAVAL_FORT_LEVEL_COLORS = {
		0.0, 	0.3, 0.3, 0.3, 0.2,
		0.0,	0.7, 0.7, 0.2, 0.3,
		1.0,	0.7, 0.2, 0.2, 0.5,
	},

	TEMPERATURE_MAP_MODE_COLORS = {
		-35.0, 	0.0, 0.0, 0.5, 1.0,
		-25.0, 	0.0, 0.0, 1.0, 1.0,
		-10.0, 	0.0, 0.7, 1.0, 1.0,
		0.0, 	0.0, 1.0, 0.45, 0.45,
		15.0,	1.0, 1.0, 0.0, 1.0,
		25.0,	1.0, 0.65, 0.0, 1.0,
		30.0,	1.0, 0.0, 0.0, 1.0,
		35.0,	0.5, 0.0, 0.0, 1.0,
	},

	RAILWAY_GUN_ASSIGNMENTS_MAP_MODE_COLORS = {
		0.0,	1.0, 0.0, 0.0, 1.0,
		0.25,	1.0, 0.65, 0.0, 1.0,
		0.75,	1.0, 1.0, 0.0, 1.0,
		1.0, 	0.0, 1.0, 0.45, 0.45,
	},

	INTEL_LEDGER_NAVY_REGION_COLOR_WITH_MISSION = { 0.7, 0.7, 0.7, 0.9 },
	INTEL_LEDGER_NAVY_REGION_COLOR_WITH_MISSION_AND_TASKFORCES_IN_REGION = { 0.8, 0.8, 0.4, 0.9 },

	INTEL_LEDGER_AIR_REGION_COLOR = { 0.8, 0.8, 0.4, 0.9 },

	INTEL_LEDGER_GRAPH_RED = { 1.0, 0.0, 0.0, 1.0 },
	INTEL_LEDGER_GRAPH_GREEN = { 0.0, 1.0, 0.0, 1.0 },

	RAID_SOURCE_MAP_STRIPES_COLOR = { 0.0, 1.0, 1.0, 0.4 },
	RAID_SOURCE_MAP_STRIPES_HOVERED_COLOR = { 0.3, 1.0, 1.0, 0.7 },

	RAID_ARROW_BALLISTIC_SHAPE = 0.02,              
	RAID_ARROW_BALLISTIC_MAX_HEIGHT = 30,			
	RAID_ARROW_BALLISTIC_MAX_SEGMENT_LENGTH = 1,	
	RAID_ARROW_BALLISTIC_MAX_SEGMENTS = 100,		

	RAID_ARROW_AIR_HEIGHT = 10.0,                   
	RAID_ARROW_AIR_SLOPE_SOURCE_STEEPNESS = 0.2,    
	RAID_ARROW_AIR_SLOPE_SOURCE_LENGTH = 50.0,      
	RAID_ARROW_AIR_SLOPE_TARGET_STEEPNESS = 0.2,    
	RAID_ARROW_AIR_SLOPE_TARGET_LENGTH = 0.0,       
	RAID_ARROW_AIR_MAX_SEGMENT_LENGTH = 1,			
	RAID_ARROW_AIR_MAX_SEGMENTS = 100,				

	RAID_ARROW_NAVAL_SUBDIVISIONS = 20,             
	RAID_ARROW_NAVAL_SHARP_TURN_SMOOTHNESS = 0.10,  
	RAID_ARROW_NAVAL_USE_MIDPOINTS = true,          

	RAID_UNIT_ENTITY_BASE_SCALE = 2.0,              
	RAID_UNIT_ENTITY_OFFSET = { 0.0, 0.0, 0.0 },    
    RAID_CONVOY_ENTITY_START_OFFSET = 15.0,         

	RAID_UNIT_SECOND_STAGE_PROGRESS = 0.33,			
	RAID_UNIT_THIRD_STAGE_PROGRESS = 0.66,			

	DEFAULT_NUDGE_FLOATING_HARBOR_DIST = 7.0,       

	RAID_MAP_ICON_DRAW_DISTANCE_MIN = 10.0,                      
	RAID_MAP_ICON_DRAW_DISTANCE_MAX = 500.0,                     
	RAID_MAP_ICON_MAX_DRAW_DISTANCE_IN_RAID_MAP_MODE = 1600.0,   

	RAID_TARGET_ZOOM_HEIGHT = 200.0,				
},

NInterface = {
	MAX_NO_FACTION_FILTER_BUTTONS = 40,			

	LOGISTICS_PAST_WEEK = 7,					

	COMBAT_SOME_PIERCING = 0.25,					
	COMBAT_GOOD_PIERCING = 0.6,					
	COMBAT_SOME_ARMOR = 0.25,					
	COMBAT_GOOD_ARMOR = 0.6,					

	MIN_FOCUS_TREE_ZOOM = 0.2,					
	MAX_FOCUS_TREE_ZOOM = 1.0,					
	FOCUS_TREE_ZOOM_SPEED = 0.16,				
	FOCUS_TREE_ZOOM_FACTOR = 0.5,				

	TOOLTIP_SCREEN_LEFT_OFFSET_X = 0,				
	TOOLTIP_SCREEN_RIGHT_OFFSET_X = 0,				
	TOOLTIP_SCREEN_TOP_OFFSET_Y = 0,				
	TOOLTIP_SCREEN_BOTTOM_OFFSET_Y = 0,				

	NO_COMBATS_COLOR = { 0.0, 0.0, 0.8 },				
	SUCCESFUL_COMBATS_COLOR = { 120.0/360.0, 0.95, 0.86 },				
	MIN_NON_SUCCESSFUL_COMBAT_COLOR = { 100.0/360.0, 0.95, 0.86 },	
	MID_NON_SUCCESSFUL_COMBAT_COLOR = { 50.0/360.0, 0.95, 0.86 },
	MAX_NON_SUCCESSFUL_COMBAT_COLOR = { 00.0/360.0, 0.95, 0.86 },	

	UNIT_SELECT_DOUBLE_CLICK_TIME = 0.1,				
	SHIP_SELECT_DOUBLE_CLICK_TIME = 1.0,				

	MINIMAP_TOGGLE_DURATION = 0.5,				
	MINIMAP_TOGGLE_SHIFT = 270,				

	TIMED_MESSAGE_TIMEOUT = 0.35,					

	MINIMAP_PING_DURATION = 12.0, 				
	MINIMAP_PING_SPEEDUP_ON_SCREEN = 2.0,		
	MINIMAP_PING_DELAY_BETWEEN_PINGS = 0.3,     

	DRAG_AND_DROP_SCROLLING_SENSITIVITY = 12.5,	
	GRIDBOX_ELEMENTS_INTERPOLATION_SPEED = 0.2,  -- Modified by mod

	ARMY_GROUP_PORTRAIT_SPACING = 6,			
	ARMY_GROUP_FIRST_MEMBER_SPACING = 5,		
	ARMY_GROUP_COLLAPSE_EXTRA_SPACING = 5,		

	ARMY_LIST_BOTTOM_PADDING = 165,				
	ARMY_LIST_BOTTOM_PADDING_WITH_EXPEDITIONARIES = 240, 

	MILITARY_FACTORIES_SCALE = { 1, 5, 10 },

	FLEET_BOTTOM_BAR_HEIGHT = 110,				
	FLEET_BOTTOM_BAR_PADDING_RIGHT = 110,			

	PICKED_UP_NAVY_OFFSET_X = 26,				
	PICKED_UP_NAVY_OFFSET_Y = -14,				

	TASK_FORCE_ENTRY_OFFSET_Y = -2,				
	TASK_FORCE_COMPOSITION_EDITOR_PADDING_TO_NAVIES_VIEW = 20,	

	FUEL_STOCKPILE_DURATION_MAX = 365*5,		

	SHIP_REFIT_TOOLTIP_MAX_DIFF_LINES = 20,		

	DEFAULT_TASKFORCE_ICON = 6,						
	DEFAULT_FLEET_ICON = 4,							
	DEFAULT_NAVAL_EQUIPMENT_ROLE_ICON = 1,			

	FUEL_GRAPH_COLOR = {
		0.8, 0.8, 0.8, 
		0.8, 0.0, 0.0, 
		0.0, 0.8, 0.0, 
		0.0, 0.0, 0.8, 
		0.0, 0.8, 0.8, 
		0.8, 0.8, 0.0, 
		0.8, 0.8, 0.8, 
	},

	PRODUCTION_SHIP_FILTERS_ROLE_SELECTION_WINDOW_OFFSET_X = 4,	
	PRODUCTION_SHIP_FILTERS_ROLE_SELECTION_WINDOW_OFFSET_Y = -8,

	SHIP_FUEL_EFFICIENCY_WARNING_THRESHOLD = 60.0,			

	NAVAL_STRIKE_FORCE_ATTACK_LIKELYHOOD_THR_VERY_LIKELY = 0.8,	
	NAVAL_STRIKE_FORCE_ATTACK_LIKELYHOOD_THR_LIKELY = 0.6,		
	NAVAL_STRIKE_FORCE_ATTACK_LIKELYHOOD_THR_UNLIKELY = 0.3,	

	CONVOY_ESCORT_PRESENCE_WARNING_THRESHOLD = 0.95,		

	MISSION_PATROL_SOFT_REQ_THRESHOLD_SURFACE_DETECTION = 22,	
	MISSION_PATROL_SOFT_REQ_THRESHOLD_SPEED = 30,			
	MISSION_PATROL_SOFT_REQ_THRESHOLD_SURFACE_VISIBILITY = 1.4,	
	MISSION_CONVOY_ESCORT_SOFT_REQ_THRESHOLD_SUB_DETECTION = 2,	
	MISSION_CONVOY_ESCORT_SOFT_REQ_THRESHOLD_DEPTH_CHARGES_AVG = 8,	
	MISSION_CONVOY_ESCORT_SOFT_REQ_THRESHOLD_DEPTH_CHARGES_SUM = 8,	
	MISSION_NAVAL_INVASION_SUPPORT_SOFT_REQ_THRESHOLD_SHORE_BOMBARDMENT = 3,	

	OPERATIVE_MISSION_EFFICIENCY_ANIMATION_TIME_MIN = 0.2,			
	OPERATIVE_MISSION_EFFICIENCY_ANIMATION_TIME_MAX = 3.0,			

	OPERATIVE_COUNTER_INTELLIGENCE_DEFENSE_TO_EFFICIENCY_FACTOR = 40.0,	
	OPERATIVE_NETWORK_STRENGTH_GAIN_TO_EFFICIENCY_FACTOR = 12.0,		
	OPERATIVE_PROPAGANDA_DRIFT_TO_EFFICIENCY_FACTOR = 130000.0,		
	OPERATIVE_BOOST_IDEOLOGY_DRIFT_TO_EFFICIENCY_FACTOR = 500.0,		
	OPERATIVE_ROOT_OUT_RESISTANCE_EFFICIENCY_TO_EFFICIENCY_FACTOR = 80.0,	
	OPERATIVE_TRADE_INFLUENCE_DRIFT_TO_EFFICIENCY_FACTOR = 135,		
	OPERATIVE_OPINION_DRIFT_TO_EFFICIENCY_FACTOR = 400,		
	OPERATIVE_TENSION_DRIFT_TO_EFFICIENCY_FACTOR = 400,		

	COUNTERINTELLIGENCE_ACTIVITY_LEVEL_THRESHOLD_VALUES = {
		10,
		20,
		50,
		100,
	},
	COUNTERINTELLIGENCE_ACTIVITY_LEVEL_THRESHOLD_COLORS = {
		{ 0.1, 0.9, 0.2, 1.0 },
		{ 0.6, 0.9, 0.2, 1.0 },
		{ 0.9, 0.7, 0.2, 1.0 },
		{ 1.0, 0.5, 0.0, 1.0 },
		{ 0.9, 0.1, 0.2, 1.0 },
	},

	GARRISON_STRENGTH_TO_SHOW_RED = 0.25,	

	MAX_DECISIONS_IN_DECISION_ALERT_TOOLTIP = 5,				
	PIXEL_OFFSET = -3, 											
	ARMY_UNIT_LEADER_ICON_SPRITE_ID = 5,
	NAVY_UNIT_LEADER_ICON_SPRITE_ID = 3,
	POLITICAL_LEADER_ICON_SPRITE_ID = 13,

	EQUIPMENT_DESIGNER_SHOW_MODULE_FORBIDS_BASE_ROLE_ICON = 0, 
	EQUIPMENT_DESIGNER_SHOW_MODULE_FORBIDS_SPECIALIZED_ROLE_ICON = 0, 

	MIO_CENTRAL_TREE_HORIZONTAL_POSITION = 1, 

	SLOW_INTERFACE_THRESHOLD = 5000, 
},


NFrontend = {
	CAMERA_LOOKAT_X = 2958.0,  -- Modified by mod
	CAMERA_LOOKAT_Y = 0.0,  -- Modified by mod
	CAMERA_LOOKAT_Z = 1519.0,  -- Modified by mod
	CAMERA_START_X = 2958.0,  -- Modified by mod
	CAMERA_START_Y = 800,  -- Modified by mod
	CAMERA_START_Z = 1400.0,  -- Modified by mod
	CAMERA_END_X = 2958.0,  -- Modified by mod
	CAMERA_END_Y = 900.0,  -- Modified by mod
	CAMERA_END_Z = 1400.0,  -- Modified by mod
	CAMERA_MIN_HEIGHT = 50.0,  -- Modified by mod
	CAMERA_MAX_HEIGHT = 3000.0,  -- Modified by mod
	CAMERA_SPEED_IN_MENUS = 0.1,  -- Modified by mod
	CAMERA_INTERPOLATION_SPEED = 0.19,  -- Modified by mod

	FRONTEND_POS_X = 2958.0,
	FRONTEND_POS_Y = 900.0,
	FRONTEND_POS_Z = 1500.0,
	FRONTEND_LOOK_X = 2958.0,
	FRONTEND_LOOK_Y = 0.0,
	FRONTEND_LOOK_Z = 1519.0,

	MP_OPTIONS_POS_X = 2958.0,
	MP_OPTIONS_POS_Y = 922.0,
	MP_OPTIONS_POS_Z = 848.0,
	MP_OPTIONS_LOOK_X = 2958.0,
	MP_OPTIONS_LOOK_Y = 0.0,
	MP_OPTIONS_LOOK_Z = 1519.0,

	NEW_GAME_BUTTON_DISABLE_DELAY_ON_INVALID_MAP_DATA = 10.0, 

	SOCIALVIEW_CONTEXT_MENU_BUTTON_OFFSET = 10,
	SOCIALVIEW_CONTEXT_MENU_MARGIN = 2,
},

NSound = {
	HEIGHT_SOUND_CATEGORY     = "Atmosphere",  
	HEIGHT_SOUND_MIN_ALTITUDE =  100.0,        
	HEIGHT_SOUND_MAX_ALTITUDE = 2000.0,        
	HEIGHT_SOUND_MIN_VOLUME   =    0.2,
	HEIGHT_SOUND_MAX_VOLUME   =    1.0,

	BATTLE_SOUND_NAME            = "amb_battle_distant",
	BATTLE_SOUND_INIT_RADIUS     =   9.0,
	BATTLE_SOUND_FALLOFF_DEFAULT = 100.0,

	BATTLE_SOUND_MIN_UNIT_COUNT =   6,

	VOICE_OVER_CATEGORY  = "Voices",
	VOICE_OVER_COOL_DOWN = 2.8, 
},

NFriendGUI = {
	OFFLINE_COLOR = { 0.7, 0.7, 0.7, 1.0}, 
	ONLINE_COLOR = { 0.56, 0.85, 0.56, 1.0 }, 
},

}